---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildpacks-ws-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildpacks-pipelinerun-
spec:
  pipelineRef:
    name: buildpacks
  podTemplate:
    securityContext:
      fsGroup: 65532 
  params:
    - name: BUILDER_IMAGE
      value: docker.io/cnbs/sample-builder:bionic@sha256:6c03dd604503b59820fd15adbc65c0a077a47e31d404a3dcad190f3179e920b5
    - name: TRUST_BUILDER
      value: "true"
    - name: APP_IMAGE
      value: ttl.sh/tekton-test:1h
    - name: SOURCE_URL
      value: https://github.com/PoisWu/docker-source-code
  workspaces:
    - name: source-ws
      subPath: source
      persistentVolumeClaim:
        claimName: buildpacks-ws-pvc-1
    - name: cache-ws
      subPath: cache
      persistentVolumeClaim:
        claimName: buildpacks-ws-pvc-1
